import { StyleSheet } from 'react-native';
import colors from '../../shared/constants/colors';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: colors.gray,
  },
  welcomeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 20,
    backgroundColor: colors.white,
  },
  welcomeTextContainer: {
    flex: 1,
  },
  welcomeText: {
    fontSize: 16,
    color: colors.gray,
  },
  userName: {
    fontSize: 28,
    fontWeight: 'bold',
    color: colors.primary,
    marginTop: 4,
  },
  welcomeSubtext: {
    fontSize: 14,
    color: colors.gray,
    marginTop: 8,
  },
  avatarContainer: {
    marginLeft: 16,
  },
  profileAvatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: colors.primary,
  },
  profileAvatarPlaceholder: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: colors.white,
  },
  profileAvatarText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.white,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    paddingHorizontal: 16,
    marginBottom: 24,
  },
  statCard: {
    flex: 1,
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    marginHorizontal: 6,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 1,
    borderColor: colors.lightGray,
    maxWidth: '50%',
  },
  statIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  statValue: {
    fontSize: 28,
    fontWeight: 'bold',
    color: colors.primary,
  },
  statLabel: {
    fontSize: 14,
    color: colors.gray,
    marginTop: 4,
  },
  featuresSection: {
    paddingHorizontal: 16,
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.black,
    marginBottom: 16,
  },
  featuresRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
  },
  featuresColumn: {
    flex: 1,
  },
  featureCard: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.lightGray,
  },
  featureIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  featureTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.black,
    marginBottom: 4,
  },
  featureDescription: {
    fontSize: 12,
    color: colors.gray,
    textAlign: 'center',
  },
  section: {
    paddingHorizontal: 16,
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  seeAllText: {
    fontSize: 14,
    color: colors.primary,
    fontWeight: '500',
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 40,
    backgroundColor: colors.lightGray,
    borderRadius: 12,
  },
  emptyStateText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.gray,
    marginTop: 12,
  },
  emptyStateSubtext: {
    fontSize: 12,
    color: colors.gray,
    marginTop: 4,
    textAlign: 'center',
  },
  bottomPadding: {
    height: 30,
  },
  // Add these styles to your existing styles
statsRow: {
  flexDirection: 'row',
  justifyContent: 'space-around',
  gap: 12,
  paddingHorizontal: 16,
  marginTop: 16,
  marginBottom: 8,
},
aiRecipeCard: {
  backgroundColor: colors.white,
  borderRadius: 16,
  marginBottom: 12,
  padding: 16,
  shadowColor: colors.black,
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.1,
  shadowRadius: 4,
  elevation: 2,
  borderWidth: 1,
  borderColor: colors.lightGray,
},
aiRecipeContent: {
  gap: 8,
},
aiBadge: {
  flexDirection: 'row',
  alignItems: 'center',
  alignSelf: 'flex-start',
  backgroundColor: colors.secondary,
  paddingHorizontal: 8,
  paddingVertical: 4,
  borderRadius: 12,
  gap: 4,
},
aiBadgeText: {
  fontSize: 10,
  color: colors.white,
  fontWeight: 'bold',
},
aiRecipeTitle: {
  fontSize: 16,
  fontWeight: 'bold',
  color: colors.black,
},
aiRecipeDescription: {
  fontSize: 13,
  color: colors.gray,
  lineHeight: 18,
},
aiMetaRow: {
  flexDirection: 'row',
  flexWrap: 'wrap',
  marginTop: 4,
},
aiMetaItem: {
  flexDirection: 'row',
  alignItems: 'center',
  marginRight: 16,
  gap: 4,
},
aiMetaText: {
  fontSize: 11,
  color: colors.gray,
},
});